#.github/workflows/linting.yaml
name: Linting Checks

on:
  pull_request:
    branches:
      - master
      - develop
    paths:
      - '**.py'
  push:
    branches:
      - '**' # Every branch
    paths:
      - '**.py'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  linting:
    env:
      GITHUB_TOKEN: ${{ secrets.GH_REPO_READ_TOKEN }}
    name: Run Linters for surfExp
    runs-on: ubuntu-latest
    environment: staging
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'

      - name: Set PATH
        run: |
          echo "/tmp/micromamba/envs/surfExp/bin" >> $GITHUB_PATH

      - name: Set python
        run: |
          poetry env use /tmp/micromamba/envs/surfExp/bin/python

      - name: Modify pyproject.toml
        run: |
          sed -i 's#git@github.com:destination-earth-digital-twins/#https://github.com/destination-earth-digital-twins/#g' pyproject.toml

      - name: Set github credentials
        uses: ./.github/actions/setup-github-credentials
        with:
          github_token: ${{ env.GITHUB_TOKEN }}

      - name: Install DEODE surfExp
        run: |
          echo micromamba_path="/tmp/micromamba/envs/surfExp/" > envs/github_env
          ./bin/install.sh github_env

      #----------------------------------------------
      #         Run the linting checks
      #----------------------------------------------
      - name: Run linters
        run: |
          poetry run poetry devtools lint
